homeassistant:
  # Customization file
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
  allowlist_external_dirs:
    - /config/

default_config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Enables System Health
system_health:

http:
  server_port: 443
  ssl_certificate: !secret http_certificate
  ssl_key: !secret http_key
  ip_ban_enabled: False
  login_attempts_threshold: 5

# MQTT Broker
#mqtt:
#  broker: core-mosquitto
#  username: !secret mqtt_user
#  password: !secret mqtt_password

# Enables wake on lan
wake_on_lan:

# Enables custom python scripts as services
python_script:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

weather:
  - platform: darksky
    name: home_weather
    mode: daily
    api_key: !secret darksky_api_key

# Text to speech
tts:
  - platform: google_translate
    language: "es"
    service_name: google_say

person:

smartir:
  check_updates: false

webostv:
  name: victor_tv
  host: !secret victor_tv_ip
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret victor_tv_mac
  customize:
    sources:
      - livetv
      - youtube
      - netflix
      - steam link

breaking_changes:

# Logs
logger:
  default: warning
  logs:
    homeassistant.components.history: debug
    homeassistant.components.recorder: debug
    homeassistant.components.xiaomi_miio: debug
    miio: debug

# Enables recorder in external database
recorder:
  db_url: !secret db_connection_str
  purge_keep_days: 3
  exclude:
    domains:
      - automation
      - camera
      - group
      - script
      - zone
    entities:
      - sensor.hass_last_version
      - sensor.last_boot
      - sensor.installed_version
      - sensor.ssl_certificate_expiry
      - sensor.laundry_time
      - sensor.entry_door_last_call
      - sensor.position_livingroom_cover1
      - sensor.main_current
      - sensor.main_energy
      - sensor.main_power
      - sensor.main_voltage
      - sensor.main_factor
      - sensor.washing_remaining

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

alexa:
  smart_home:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

stream:

utility_meter:
  energy:
    name: energy_utility_meter
    source: sensor.main_total_daily_energy
    cycle: daily
    tariffs:
      - Punta
      - Llano
      - Valle

plant:
  dracena_marginata:
    sensors:
      #battery: sensor.dracena_marginata_battery
      brightness: sensor.dracena_marginata_illuminance
      conductivity: sensor.dracena_marginata_soil_conductivity
      moisture: sensor.dracena_marginata_moisture
      temperature: sensor.dracena_marginata_temperature
    min_brightness: 1500
    max_brightness: 6000
    min_conductivity: 350
    max_conductivity: 2000
    min_moisture: 15
    max_moisture: 60
    min_temperature: 10
    max_temperature: 32

# INCLUDE REGION #
automation: !include automations.yaml
script: !include scripts.yaml
google_assistant: !include google_assistant.yaml

binary_sensor: !include_dir_list binary_sensors/
camera: !include_dir_list cameras/
climate: !include_dir_list climates/
cover: !include_dir_list covers/
fan: !include_dir_list fans/
#light: !include_dir_list lights/
#media_player: !include_dir_list media_players/
notify: !include_dir_list notifications/
#remote: !include_dir_list remotes/
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
