name: home
views:
  - id: 0  # Automatically created id
    title: Hogar
    icon: mdi:home
    cards:
      - id: 5b888c1a719943d4b399ab4c0859156f  # Automatically created id
        type: weather-forecast
        entity: weather.home_weather
      - id: b4c0286aea884040a6a6edce0d2c70b5  # Automatically created id
        type: entities
        title: Tiburones
        entities:
          - device_tracker.google_maps_103784348845750761493
          - device_tracker.google_maps_110963040061122904230
      - id: c6e143a55c7e4f19a46f965dd54790a1  # Automatically created id
        type: entities
        title: Baño
        entities:
          - sensor.bathroom_temperature
          - sensor.bathroom_humidity
          - switch.bathroom_heater
          - switch.towel_warmer
      - type: thermostat
        entity: climate.bathroom_climate
      - type: thermostat
        entity: climate.livingroom_climate
      - id: 146f2b761ddc4a7fb134106a47aa7c35  # Automatically created id
        type: entities
        title: Salón
        entities:
          - climate.livingroom_climate
          - sensor.livingroom_ble_sensor_temperature
          - sensor.livingroom_ble_sensor_humidity
          - fan.livingroom_fan
          - switch.victor_monitor
          - switch.victor_pc
          - switch.desktop_lamp
          - switch.victor_s2
          - switch.livingroom_heater
          - switch.sofa_lamp
          - switch.nas
          - switch.rafa_pc
          - switch.rafa_pc_work
          - cover.livingroom_cover1
      - id: a77a1696530f439bb9f84045fa6534bc  # Automatically created id
        type: entities
        title: Salón IR
        entities:
          - switch.livingroom_fan_light
      - id: 1b9da018308547759fe65443d573339f  # Automatically created id
        type: vertical-stack
        cards:
          - type: glance
            title: Consumo General
            entities:
              - sensor.main_voltage
              - sensor.main_current
              - sensor.main_power
              - sensor.main_energy
              - sensor.main_factor
          - type: glance
            title: Consumo Aire acondicionado
            entities:
              - sensor.rafa_blitzwolf_voltage
              - sensor.rafa_blitzwolf_current
              - sensor.rafa_blitzwolf_power
              - sensor.rafa_blitzwolf_energy
      - id: 3a1df9c8038343b9baf2eb51b08b0794  # Automatically created id
        type: entities
        title: Lavadora
        entities:
          - sensor.washing_machine_energy
          - sensor.washing_machine_power
          - sensor.laundry_state
          - sensor.laundry_time
          - input_text.washing_machine_start_hour
          - switch.washing_machine
      - id: a3b8dbe3f0b3403fab475f9a8948ec88  # Automatically created id
        type: entities
        title: Entrada
        entities:
          - script.open_entry_door
          - sensor.entry_door_last_call
  - id: 1  # Automatically created id
    title: V
    cards:
      - id: 3ff485394ebc4ce3b3a0e2529513db53  # Automatically created id
        type: entities
        title: Interruptores
        entities:
          - switch.victor_insecticide
          - switch.victor_bedside_lamp
          - light.victor_rgbw_leds
          - switch.victor_sonoff_pow
          - switch.watering
          - fan.victor_fan
          - cover.victor_cover
      - id: 30a97f2f062840cb9474409145618b85  # Automatically created id
        type: sensor
        entity: sensor.victor_ble_sensor_temperature
        height: 75
        line_color: '#ff9900'
      - id: 4f375c3bb0b44878afe0623afa4eb2da  # Automatically created id
        type: sensor
        entity: sensor.victor_ble_sensor_humidity
        height: 75
        line_color: '#3498db'
      - id: c5c9d6d393274fe19e90530f4636cbe4  # Automatically created id
        type: entities
        title: Climatizador
        entities:
          - sensor.victor_ble_sensor_temperature
          - sensor.victor_ble_sensor_humidity
      - id: e670a719eccf4f4f94fbcfa5d4259f17  # Automatically created id
        type: thermostat
        entity: climate.victor_climate
      - id: a20594eedcb64f9a9fac4886bf5087e1  # Automatically created id
        type: media-control
        entity: media_player.victor_tv
      - id: 2322586535c644a8b3b4d5ee8f51303c  # Automatically created id
        type: media-control
        entity: media_player.victor_bedroom_speaker
  - id: 2  # Automatically created id
    title: R
    cards:
      - id: d80b55df0be04784b7bd5c9b9a1e2f75  # Automatically created id
        type: entities
        title: Climatizador
        entities:
          - sensor.rafa_ble_sensor_temperature
          - sensor.rafa_ble_sensor_humidity
      - type: thermostat
        entity: climate.rafa_climate
      - id: 84f89b6e904c40f58369d44c3064d75a  # Automatically created id
        type: entities
        title: Interruptores
        entities:
          - switch.rafa_fan
          - switch.rafa_extender
          - light.rafa_rgb_leds
          - switch.rafa_broadlink_s1
          - switch.rafa_broadlink_s2
          - switch.rafa_broadlink_s3
          - switch.rafa_broadlink_s4
          - switch.rafa_blitzwolf
      - id: a6b8ba5349f741c997155e693997e92a  # Automatically created id
        type: media-control
        entity: media_player.av_player
      - type: media-control
        entity: media_player.googlehome8237
  - id: 3  # Automatically created id
    title: Camaras
    icon: mdi:cctv
    cards:
      - id: 8f6ea0267cd94129856d57bdccfd0c63  # Automatically created id
        type: picture-entity
        entity: camera.luis_de_morales
      - id: 0de38c27a71c4d7bba257a220f84c995  # Automatically created id
        type: picture-entity
        entity: camera.santa_justa
      - id: d886507e257e48369978afb9df3226ef  # Automatically created id
        type: picture-entity
        entity: camera.xiaofang
  - id: 4  # Automatically created id
    title: Escenas
    icon: mdi:buffer
    cards:
      - id: af6513b21bfe4a82907479cef8258145  # Automatically created id
        type: horizontal-stack
        cards:
          - type: gauge
            title: Uso CPU
            entity: sensor.processor_use
            severity:
              green: 0
              yellow: 45
              red: 85
          - type: gauge
            title: Uso RAM
            entity: sensor.memory_use_percent
            severity:
              green: 0
              yellow: 45
              red: 80
      - id: 5cd7b480f79542399f8805ea0f3da405  # Automatically created id
        type: entities
        title: Monitor sistema
        entities:
          - sensor.processor_use
          - sensor.disk_free
          - sensor.memory_use_percent
          - sensor.home_assistant_v2_db
          - sensor.last_boot
          - sensor.hass_last_version
          - sensor.installed_version
          - sensor.ssl_certificate_expiry
      - id: 8e3e05146a1c46f88a0a1360416444b2  # Automatically created id
        type: entities
        title: Estado de baterías
        entities:
          - sensor.livingroom_ble_sensor_battery
          - sensor.victor_ble_sensor_battery
          - sensor.rafa_ble_sensor_battery
      - id: 4be11987d1e84fd19f1fbc3e55f665b8  # Automatically created id
        type: markdown
        title: NAS
        content: >-
          [Freenas](http://192.168.1.110)

          [Netdata](http://192.168.1.110/netdata)

          [Plex Media Server](http://192.168.1.97:32400)

          [Radarr](http://192.168.1.94:7878/)

          [Sonarr](http://192.168.1.96:8989)

          [Jackett](http://192.168.1.95:9117)

          [Transmission](http://192.168.1.98:9091)
