esphomeyaml:
  name: livingroom_ble_tracker
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.124
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

sensor:
  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:D9:79:0E
    temperature:
      name: livingroom_temperature
    humidity:
      name: livingroom_humidity
    battery_level:
      name: livingroom_battery
  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:D1:26:45
    temperature:
      name: victor_temperature
    humidity:
      name: victor_humidity
    battery_level:
      name: victor_battery
  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:D3:D3:80
    temperature:
      name: rafa_temperature
    humidity:
      name: rafa_humidity
    battery_level:
      name: rafa_battery