#SP10 Module
substitutions:
  hostname: 2relay_test
  upper_hostname: "2Relay_Wall Test"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp12e

<<: !include .common.wifi.yaml

# Enable logging
logger:

status_led:
  pin:
    number: GPIO2
    inverted: true
    
dallas:
  - pin: GPIO2
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: True
    id: button_1
    name: "$upper_hostname Button1"
    on_state :
      - switch.toggle: relay_1
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    id: sensor_1
    name: "$upper_hostname Sensor1"
    filters:
      - delayed_off: 500ms
  - platform: gpio
    pin:
      number: GPIO12
      inverted: True
    id: button_2
    name: "$upper_hostname Button2"
    on_state :
      - switch.toggle: relay_2
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    id: sensor_2
    name: "$upper_hostname Sensor2"
    filters:
      - delayed_off: 500ms
      
sensor:
  - platform: adc
    pin: A0
    name: "$upper_hostname Brightness"
    icon: mdi:brightness-percent
    unit_of_measurement: "%"
    update_interval: 3s
    filters:
      - multiply: 100
  - platform: dallas
    address: 0x5A01193969832F28
    name: "$upper_hostname Temperature"
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    pin: GPIO5
    id: relay_1
    name: "$upper_hostname Relay1"
    restore_mode: restore_default_off
  - platform: gpio
    pin: GPIO13
    id: relay_2
    name: "$upper_hostname Relay2"
    restore_mode: restore_default_off