#SP10 Module
substitutions:
  hostname: bathroom-plug
  upper_hostname: "Bathroom Plug"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

<<: !include .common.wifi.yaml

# Enable logging
logger:
  baud_rate: 0 # Disable UART (GPIO3 RX)

web_server:
  port: 80

status_led:
  pin:
    number: GPIO13
    inverted: true
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Triple Clicked"
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
      - timing:
          - ON for at least 2s
        then:
          - logger.log: "Single Long Clicked"
          - light.toggle: light_1
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - switch.toggle: relay_1

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO1

switch:
  - platform: gpio
    name: $upper_hostname
    pin: GPIO14
    id: relay_1
    restore_mode: restore_default_off
    
light:
  - platform: monochromatic
    name: "$upper_hostname Light"
    id: light_1
    output: output_component1
    
sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO4
    cf1_pin: GPIO5
    current_resistor: 0.001 ohm
    voltage_divider: 2401
    change_mode_every: 1
    update_interval: 10s
    current:
      name: "$upper_hostname Current"
      unit_of_measurement: A
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 0.0 #Need to keep 0 mapped to 0 for when connected device is not drawing any power
            - 7.4 -> 6.103 #Tested using a meter and 6.122A toaster -0.019A from just this plug with toaster off
    voltage:
      name: "$upper_hostname Voltage"
      unit_of_measurement: V
      filters:
        - offset: -480 #value was 712.0
    power:
      name: "$upper_hostname Power"
      unit_of_measurement: W
      id: wattage
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 0.0 #Need to keep 0 mapped to 0 for when connected device is not drawing any power
            - 4054.3 -> 721.2 #Tested using a meter and 722.0W toaster -0.8W from just this plug with toaster off