substitutions:
  hostname: bed_frame_light
  upper_hostname: "Bed Frame"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

<<: !include .common.wifi.yaml

# Enable logging
logger:
  baud_rate: 0 # Disable UART (GPIO3 RX)

status_led:
  pin:
    number: GPIO2
    inverted: yes
    
sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "$upper_hostname Motion Left"
    id: motion_left
    device_class: motion
    on_press:
      then:
        - light.turn_on: light_left
    on_release:
      then:
        - light.turn_off: light_left
  - platform: gpio
    pin: GPIO3
    name: "$upper_hostname Motion Right"
    id: motion_right
    device_class: motion
    on_press:
      then:
        - light.turn_on: light_right
    on_release:
      then:
        - light.turn_off: light_right

light:
  - platform: cwww
    name: "$upper_hostname Light Left"
    id: light_left
    cold_white: output_g
    warm_white: output_r
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
  - platform: cwww
    name: "$upper_hostname Light Right"
    id: light_right
    cold_white: output_b
    warm_white: output_w
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_g
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_r
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_b
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_w
    pin: GPIO13
  