substitutions:
  hostname: entry_door_light
  upper_hostname: "Entry door Lifht"
  
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

<<: !include .common.wifi.yaml

# Enable logging
logger:

status_led:
  pin:
    number: GPIO13
    inverted: true
    
sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: 
          id: relay_1

  - platform: gpio
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - switch.turn_on:
            id: relay_1
    on_release:
      then:
        - switch.turn_off:
            id: relay_1

switch:
  - platform: gpio
    name: $upper_hostname
    icon: mdi:lightbulb_outline
    pin: GPIO12
    id: relay_1
    restore_mode: restore_default_off
  