esphome:
  name: esp32_display
  platform: ESP32
  board: ttgo-lora32-v1  
  includes:
    - custom_components/tft_espi_display.h
    - custom_components/tft_espi_display.cpp

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: GPIO2

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
# - platform: ssd1306_spi
#   cs_pin: GPIO11
#   dc_pin: GPIO11
#   model: "SSD1306_128X64"

custom_component:
  - lambda: |-
      auto my_sensor = new esphome::tft_espi::TFT_eSPI();
      App.register_component(my_sensor);
      return {my_sensor};
      
output:
  - platform: gpio
    pin: GPIO14
    id: back_light
    
light:
  - platform: binary
    output: back_light
    name: "BackLight"
