substitutions:
  hostname: floorlamp
  upper_hostname: "Lampara pié"
  
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  
external_components:
  - source: overriden_components
    components: [ tuya ]

<<: !include .common.wifi.yaml

# Enable logging
logger:
  baud_rate: 0
  level: verbose

web_server:
  port: 80

status_led:
  pin:
    number: GPIO14
    inverted: true

uart:
  id: uart1
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3

tuya:

light:
  - platform: tuya
    name: $upper_hostname
    switch_datapoint: 1
    dimmer_datapoint: 2
    min_value: 44
    max_value: 110