substitutions:
  hostname: htu21d_sample
  upper_hostname: "HTU21D"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $hostname
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: GPIO2
    inverted: true

i2c:
  sda: GPIO4
  scl: GPIO5

sensor:
  - platform: htu21d
    temperature:
      name: "$upper_hostname Temperature"
    humidity:
      name: "$upper_hostname Humidity"
    update_interval: 10s