#SP10 Module
substitutions:
  hostname: kitchen1
  upper_hostname: "Kitchen"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp12e

<<: !include .common.wifi.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: open_door
      then:
        - output.turn_on: relay_2
        - delay: 1s
        - output.turn_off: relay_2

status_led:
  pin:
    number: GPIO2
    inverted: true
    
sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "$upper_hostname Uptime Sensor"
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: True
    id: switch_1
    on_state :
      - light.toggle: light_1
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    id: ring_detector
    device_class: sound
    name: "$upper_hostname Entryphone"
    filters:
      - delayed_off: 500ms
    on_press:
      - logger.log: "Ring detected"
      
output:
  - platform: gpio
    pin: GPIO13
    id: relay_1
  - platform: gpio
    pin: GPIO5
    id: relay_2
    
light:
  - platform: binary
    output: relay_1
    id: light_1
    restore_mode: restore_default_off
    name: "$upper_hostname Main Light"