esphome:
  name: kitchen1
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
    
status_led:
  pin:
    number: GPIO2
    inverted: yes
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: builtin_btn
    
  - platform: gpio
    pin:
      number: GPIO3
    name: "doorbell"
    
  - platform: gpio
    pin:
      number: GPIO14
      inverted: True
    id: kitchen_main_switch
    on_state:
      - switch.toggle: relay2
    
output:
  - platform: gpio
    pin: GPIO1
    id: relay3
    
switch:
  - platform: gpio
    name: "kitchen_extractor"
    pin: GPIO13
    id: relay1
    
  - platform: gpio
    name: "kitchen_main_light"
    pin: GPIO5
    id: relay2
  
  - platform: template
    name: "entry_door"
    icon: "mdi:login"
    turn_on_action:
    - output.turn_on: relay3
    - delay: 1s
    - output.turn_off: relay3