substitutions:
  hostname: kitchen_extractor
  upper_hostname: "Extractor"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

<<: !include .common.wifi.yaml

# Enable logging
logger:
  baud_rate: 0

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s
#  - platform: dht
#    pin: GPIO14
#    model: DHT11
#    temperature:
#      name: "Kitchen Temperature"
#    humidity:
#      name: "Kitchen Humidity"
#    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
    id: wall_switch
    on_state:
      - switch.toggle: relay

script:
  - id: timer_off
    then:
    - delay: 90min
    - switch.turn_off: relay

switch:
  - platform: gpio
    name: $upper_hostname
    id: relay
    icon: mdi:radiator
    pin: GPIO12
    restore_mode: restore_default_off
    on_turn_on:
      - script.execute: timer_off
    on_turn_off:
      - script.stop: timer_off