#SP10 Module
substitutions:
  hostname: livingroom_switch
  upper_hostname: "Livingroom Switch"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp12e

<<: !include .common.wifi.yaml

# Enable logging
logger:

status_led:
  pin:
    number: GPIO2
    inverted: true
    
#dallas:
#  - pin: GPIO2
#      
#sensor:
#  - platform: adc
#    pin: A0
#    name: "$upper_hostname Brightness"
#    icon: mdi:brightness-percent
#    unit_of_measurement: "%"
#    update_interval: 3s
#    filters:
#      - multiply: 100
#  - platform: dallas
#    address: 0x5A01193969832F28
#    name: "$upper_hostname Temperature"
#  - platform: wifi_signal
#    name: "$upper_hostname WiFi Signal"
#    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: button_1
    pin:
      number: GPIO4
      inverted: True
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${hostname} button_1 Single Long"
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: ${hostname} button_1
                type: single_long
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${hostname} button_1 Single Short"
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: ${hostname} button_1
                type: single_short
  - platform: gpio
    id: button_2
    pin:
      number: GPIO14
      inverted: True
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${hostname} button_2 Single Long"
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: ${hostname} button_2
                type: single_long
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${hostname} button_2 Single Short"
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: ${hostname} button_2
                type: single_short
          - light.toggle: light_1
  - platform: gpio
    id: button_3
    pin:
      number: GPIO12
      inverted: True
    on_multi_click:
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${hostname} button_3 Single Long"
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: ${hostname} button_3
                type: single_long
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${hostname} button_3 Single Short"
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: ${hostname} button_3
                type: single_short

output:
  - platform: gpio
    pin: GPIO5
    id: relay_1

  - platform: gpio
    pin: GPIO13
    id: relay_2
    
light:
  - platform: binary
    output: relay_2
    id: light_1
    name: "livingroom_table_light"