substitutions:
  hostname: "livingroom_cover1"
  open_duration: 17s
  close_duration: 16s
  max_duration: 19s
  
esphome:
  name: livingroom_cover1
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: true
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $hostname
    password: "5VsLH03EpOZM"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

captive_portal:

status_led:
  pin:
    number: GPIO2
    inverted: yes

binary_sensor:
- platform: gpio
  pin:
    number: GPIO4
    inverted: yes
  id: switch_close
  on_press:
    then:
      - cover.stop: my_cover
      - cover.close: my_cover
  on_release:
    then:
      - cover.stop: my_cover
- platform: gpio
  pin:
    number: GPIO14
    inverted: yes
  id: switch_open
  on_press:
    then:
      - cover.stop: my_cover
      - cover.open: my_cover
  on_release:
    then:
      - cover.stop: my_cover
- platform: template
  id: dummy_endstop

switch:
  - platform: gpio
    pin: GPIO5
    id: cover_up
    interlock: &interlock_group [cover_up, cover_down]
    restore_mode: always off
  - platform: gpio
    pin: GPIO13
    id: cover_down
    interlock: *interlock_group
    restore_mode: always off

cover:
#- platform: time_based
- platform: endstop
  name: $hostname
  id: my_cover
  open_endstop: dummy_endstop
  close_endstop: dummy_endstop
  open_action:
    - switch.turn_on: cover_up
  open_duration: $open_duration
  close_action:
    - switch.turn_on: cover_down
  close_duration: $close_duration
  stop_action:
    - switch.turn_off: cover_up
    - switch.turn_off: cover_down
  max_duration: $max_duration