substitutions:
  hostname: livingroom_ble_tracker
  upper_hostname: "BLE RF Bridge"
  delayed_off: 100ms
  delayed_off_motion: 5s

esphome:
  name: $hostname
  platform: ESP32
  board: nodemcu-32s
  platformio_options:
    board_build.partitions: min_spiffs.csv

<<: !include .common.wifi.yaml

# Enable logging
logger:

#web_server:
#  port: 80

status_led:
  pin:
    number: GPIO2
    
#remote_receiver:
#  pin: 
#    number: GPIO32
#  dump: rc_switch
#  tolerance: 50
#  filter: 4us
#  idle: 4ms

esp32_ble_tracker:

sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s
  - platform: xiaomi_lywsdcgq
    mac_address: 4C:65:A8:D1:26:45
    temperature:
      name: lab_temperature
    humidity:
      name: lab_humidity
    battery_level:
      name: lab_ble_sensor_battery
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:04:49:93
    bindkey: "a5b55f757bbc69fbd3b4973e969a24d4"
    temperature:
      name: livingroom_temperature
    humidity:
      name: livingroom_humidity
    battery_level:
      name: livingroom_ble_sensor_battery
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:D0:FC:E8
    bindkey: "eb4101452a0437b46adeaf0d62020402"
    temperature:
      name: bathroom_temperature
    humidity:
      name: bathroom_humidity
    battery_level:
      name: bathroom_ble_sensor_battery
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:74:85:0F
    bindkey: "60ab373aa694264cbdd9c055dcb2faf4"
    temperature:
      name: bedroom_temperature
    humidity:
      name: bedroom_humidity
    battery_level:
      name: bedroom_ble_sensor_battery
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:A4:EB:AA
    bindkey: "a9711e35e5bbdb9b58ba15aa27d4abe0"
    temperature:
      name: kitchen_temperature
    humidity:
      name: kitchen_humidity
    battery_level:
      name: kitchen_ble_sensor_battery
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:62:D1:1D
    bindkey: "a6c283be56989342f1438df09b62c03f"
    temperature:
      name: guests_temperature
    humidity:
      name: guests_humidity
    battery_level:
      name: guests_ble_sensor_battery
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6D:DA:7E'
    temperature:
      name: "Dracena Marginata Temperature"
    moisture:
      name: "Dracena Marginata Moisture"
    illuminance:
      name: "Dracena Marginata Illuminance"
    conductivity:
      name: "Dracena Marginata Soil Conductivity"
    battery_level:
      name: "Dracena Marginata Battery Level"
      
#binary_sensor:
#  #Livingroom Motion
#  - platform: remote_receiver
#    name: "Livingroom Motion"
#    device_class: motion
#    rc_switch_raw:
#      code: '110101000110000000001010'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off_motion
#
#  - platform: remote_receiver
#    name: "Livingroom Motion Battery"
#    device_class: battery
#    rc_switch_raw:
#      code: '110101000110000000001111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#      
#  #Bathroom Motion
#  - platform: remote_receiver
#    name: "Bathroom Motion"
#    device_class: motion
#    rc_switch_raw:
#      code: '001101100110010000001010'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off_motion
#
#  #Bathroom Motion Battery
#  - platform: remote_receiver
#    name: "Bathroom Motion Battery"
#    device_class: battery
#    rc_switch_raw:
#      code: '001101100110010000001111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#  
#  #Bathroom Door
#  - platform: remote_receiver
#    id: door_bathroom_open
#    internal: true
#    rc_switch_raw:
#      code: '101000110111101000001110'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#    on_press:
#      - binary_sensor.template.publish:
#          id: door_bathroom
#          state: ON
#      
#  - platform: remote_receiver
#    id: door_bathroom_closed
#    internal: true
#    rc_switch_raw:
#      code: '101000110111101000000111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#    on_press:
#      - binary_sensor.template.publish:
#          id: door_bathroom
#          state: OFF
#
#  - platform: template
#    name: "Bathroom Door"
#    id: door_bathroom
#    device_class: door
#
#  #Bathroom Door Battery
#  - platform: remote_receiver
#    name: "Bathroom Door Battery"
#    device_class: battery
#    rc_switch_raw:
#      code: '101000110111101000001111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#  
#  #Entrance Door Tamper
#  - platform: remote_receiver
#    name: "Entrance Door Tamper"
#    device_class: safety
#    rc_switch_raw:
#      code: '010101111001010110011011'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#  
#  #Entrance Door
#  - platform: remote_receiver
#    id: door_entrance_open
#    internal: true
#    rc_switch_raw:
#      code: '010101111001010110011110'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#    on_press:
#      - binary_sensor.template.publish:
#          id: door_entrance
#          state: ON
#      
#  - platform: remote_receiver
#    id: door_entrance_closed
#    internal: true
#    rc_switch_raw:
#      code: '010101111001010110010111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#    on_press:
#      - binary_sensor.template.publish:
#          id: door_entrance
#          state: OFF
#
#  - platform: template
#    name: "Entrance Door"
#    id: door_entrance
#    device_class: door
#
#  #Entrance Door Battery
#  - platform: remote_receiver
#    name: "Entrance Door Battery"
#    device_class: battery
#    rc_switch_raw:
#      code: '010101111001010110011111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#    
#  
#  #Patio Door Tamper
#  - platform: remote_receiver
#    name: "Patio Door Tamper"
#    device_class: safety
#    rc_switch_raw:
#      code: '001010101010010110011011'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#  
#  #Patio Door Battery
#  - platform: remote_receiver
#    name: "Patio Door Battery"
#    device_class: battery
#    rc_switch_raw:
#      code: '001010101010010110011111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#  
#  #Patio Door
#  - platform: remote_receiver
#    id: door_patio_open
#    internal: true
#    rc_switch_raw:
#      code: '001010101010010110011110'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#    on_press:
#      - binary_sensor.template.publish:
#          id: door_patio
#          state: ON
#      
#  - platform: remote_receiver
#    id: door_patio_closed
#    internal: true
#    rc_switch_raw:
#      code: '001010101010010110010111'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
#    on_press:
#      - binary_sensor.template.publish:
#          id: door_patio
#          state: OFF
#
#  - platform: template
#    name: "Patio Door"
#    id: door_patio
#    device_class: door
#  
#  #Kitchen Smoke Alarm
#  - platform: remote_receiver
#    name: "Kitchen Smoke Alarm"
#    device_class: smoke
#    rc_switch_raw:
#      code: '011011001011000110110110'
#      protocol: 1
#    filters:
#      delayed_off: $delayed_off
