substitutions:
  hostname: "livingroom_touch"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

<<: !include .common.wifi.yaml

# Enable logging
logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: "livingroom_button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Triple Clicked"
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: $hostname
                type: triple
      - timing:
          - ON for at most 1s
          - OFF for at most 0.5s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: $hostname
                type: double
      - timing:
          - ON for at least 2s
        then:
          - logger.log: "Single Long Clicked"
          - light.toggle: led_indicator
          - delay: 0.2s
          - light.toggle: led_indicator
          - delay: 0.2s
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: $hostname
                type: single_long
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - light.toggle: led_indicator
          - delay: 0.1s
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                source: $hostname
                type: single_short

output:
  - platform: gpio
    pin: GPIO13
    inverted: yes
    id: led

  - platform: gpio
    pin: GPIO12
    id: relay
    
light:
  - platform: binary
    output: led
    id: led_indicator
    name: "livingroom_led_indicator"

  - platform: binary
    output: relay
    name: "livingroom_table_light"