substitutions:
  hostname: "livingroom_cover4"
  open_duration: 26s
  close_duration: 25s
  max_duration: 28s

esphome:
  name: $hostname
  platform: ESP8266
  board: esp_wroom_02 #Shelly 2.5 2MB
  esp8266_restore_from_flash: true 

<<: !include .common.wifi.yaml

# Enable logging
logger:

web_server:
  port: 80

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953
    voltage:
      name: "$hostname Voltage"
      internal: true
    current_a:
      internal: true
      name: "$hostname Current B"
    current_b:
      internal: true
      name: "$hostname Current A"
    active_power_a:
      name: "$hostname Active Power B"
      internal: true
      filters:
        - multiply: -1
    active_power_b:
      name: "$hostname Active Power A"
      internal: true
      filters:
        - multiply: -1
    update_interval: 1s

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: "$hostname Temp"
    internal: true
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes

binary_sensor:
- platform: gpio
  pin:
    number: GPIO13
  id: switch_close
  on_press:
    then:
      - cover.stop: my_cover
      - cover.close: my_cover
  on_release:
    then:
      - cover.stop: my_cover
- platform: gpio
  pin:
    number: GPIO5
  id: switch_open
  on_press:
    then:
      - cover.stop: my_cover
      - cover.open: my_cover
  on_release:
    then:
      - cover.stop: my_cover
- platform: template
  id: dummy_endstop

switch:
  - platform: gpio
    pin: GPIO4
    id: cover_up
    interlock: &interlock_group [cover_up, cover_down]
    restore_mode: always off
  - platform: gpio
    pin: GPIO15
    id: cover_down
    interlock: *interlock_group
    restore_mode: always off

cover:
#- platform: time_based
- platform: endstop
  name: $hostname
  id: my_cover
  open_endstop: dummy_endstop
  close_endstop: dummy_endstop
  open_action:
    - switch.turn_on: cover_up
  open_duration: $open_duration
  close_action:
    - switch.turn_on: cover_down
  close_duration: $close_duration
  stop_action:
    - switch.turn_off: cover_up
    - switch.turn_off: cover_down
  max_duration: $max_duration