substitutions:
  hostname: primary-wattmeter
  upper_hostname: "Primary Wattmeter"
  meter_name: Primary
  sensor_interval: 3s

esphome:
  name: $hostname

esp8266:
  board: esp01_1m

external_components:
  - source: overrided_components
    components: [ uart ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $hostname
    password: !secret wifi_ap_password

captive_portal:

# Enable over-the-air updates
ota:

# Enable Home Assistant API
api:

# Enable logging
logger:
  #level: VERBOSE
  baud_rate: 0

status_led:
  pin:
    number: GPIO12
    inverted: true

output:
  - platform: gpio
    id: external_green_led
    pin: GPIO2
    inverted: true
  - platform: gpio
    id: external_red_led
    pin: GPIO12
    inverted: true
  - platform: gpio
    id: internal_red_led
    pin: GPIO14
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    id: button
    name: "$upper_hostname Button"
    #on_press:
    #  - output.turn_on: external_red_led
    #  - output.turn_on: internal_red_led
    #on_release:
    #  - output.turn_off: external_red_led
    #  - output.turn_off: internal_red_led

uart:
  - id: rs485_uart
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600
    #debug:
  - id: v9261f_uart
    rx_pin: GPIO4
    tx_pin: GPIO5
    baud_rate: 4800
    parity: ODD
    stop_bits: 1
    debug:

#tuya:
#  uart_id: rs485_uart
  
dallas:
  - pin: GPIO13

modbus:
  flow_control_pin: GPIO15
  uart_id: rs485_uart

# SUN2000 Modbus reference: https://gitlab.com/Emilv2/huawei-solar/-/blob/master/src/huawei_solar/huawei_solar.py
modbus_controller:
  - id: huawei
    address: 0
    setup_priority: -10
    update_interval: $sensor_interval

sensor:
  - platform: uptime
    name: "$upper_hostname Uptime"
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s
  - platform: v9261f
    uart_id: v9261f_uart
    voltage:
      name: "$meter_name Voltage"
    current:
      name: "$meter_name Current"
    power:
      name: "$meter_name Power"
    energy:
      name: "$meter_name Total Energy"
    frequency:
      name: "$meter_name Frequency"
    update_interval: $sensor_interval
    #on_value:
    #  then:
    #    - output.turn_on: external_red_led
    #    - delay: 100ms
    #    - output.turn_off: external_red_led
    #    - delay: 100ms
    #    - output.turn_on: external_red_led
    #    - delay: 100ms
    #    - output.turn_off: external_red_led
  - platform: dallas
    address: 0xa800000c5a365b28
    name: "$meter_name External Temperature"
    
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "$meter_name Power Factor"
    address: 32084
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    device_class: power_factor
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Power Grid Voltage"
    address: 32066
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: voltage
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Power Grid Current"
    address: 32072
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    device_class: current
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar PV1 String Voltage"
    address: 32016
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: voltage
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar PV1 String Current"
    address: 32017
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    device_class: Current
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Active Power"
    id: solar_active_power
    address: 32080
    unit_of_measurement: "kW"
    register_type: holding
    value_type: S_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    device_class: energy
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: solar_active_power
              below: 10
          then:
            - output.turn_on: external_green_led
            - delay: 100ms
            - output.turn_off: external_green_led
      
      - if:
          condition:
            sensor.in_range:
              id: solar_active_power
              above: 10
          then:
            - output.turn_on: external_green_led
            - delay: 500ms
            - output.turn_off: external_green_led
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Efficiency"
    address: 32086
    unit_of_measurement: "%"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Internal Temperature"
    address: 32087
    unit_of_measurement: "°C"
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Insulation"
    address: 32088
    unit_of_measurement: "MΩ"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter State 1"
    address: 32000
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter State 2"
    address: 32002
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter State 3"
    address: 32003
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Alarm 1"
    address: 32008
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic
    icon: mdi:alert
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Alarm 2"
    address: 32009
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    entity_category: diagnostic
    icon: mdi:alert
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Alarm 3"
    address: 32010
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    entity_category: diagnostic
    icon: mdi:alert
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Device status"
    address: 32089
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    entity_category: diagnostic
    icon: mdi:lightning-bolt-circle
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Fault Code"
    address: 32090
    unit_of_measurement: ""
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    entity_category: diagnostic
    icon: mdi:alert
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Startup Time"
    address: 32091
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 0
    device_class: timestamp
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Inverter Shutdown Time"
    address: 32093
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 0
    device_class: timestamp
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Today's Energy Production"
    address: 32114
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Total Energy Production"
    address: 32106
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Total Energy Exported"
    address: 37119
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: huawei
    name: "Solar Total Energy Grid"
    address: 37121
    unit_of_measurement: "kWh"
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.01
  
  
  #- platform: huawei_solar
  #  power_factor:
  #    name: "$meter_name Power Factor"
  #  phase_a:
  #    voltage:
  #        name: "Power Grid Voltage"
  #    current:
  #        name: "Power Grid Current"
  #  pv1:
  #    voltage:
  #        name: "Solar PV1 String Voltage"
  #    current:
  #        name: "Solar PV1 String Current"
  #  active_power:
  #    name: "Solar Inverter Active Power"
  #  efficiency:
  #    name: "Solar Inverter Efficiency"
  #  inverter_inner_temp:
  #    name: "Solar Inverter Internal Temperature"
  #  insulation:
  #    name: "Solar Inverter Insulation"
  #  today_energy_production:
  #    name: "Solar Today's Energy Production"
  #  total_energy_production:
  #    name: "Solar Total Energy Production"
  #  today_energy_grid:
  #    name: "Solar Today's Energy Grid"
  #  total_energy_grid:
  #    name: "Solar Total Energy Grid"
  #  today_energy_exported:
  #    name: "Solar Today's Energy Exported"
  #  total_energy_exported:
  #    name: "Solar Total Energy Exported"
  #  update_interval: $sensor_interval

  #- platform: tuya
  #  name: "Voltage"
  #  sensor_datapoint: 101
  #- platform: tuya
  #  name: "Current"
  #  sensor_datapoint: 102
  #- platform: tuya
  #  name: "Power"
  #  sensor_datapoint: 103
  #- platform: tuya
  #  name: "Energy"
  #  sensor_datapoint: 104