substitutions:
  hostname: rowenta_fan
  upper_hostname: "Ventilador Pié"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $hostname
    password: "5VsLH03EpOZM"

captive_portal:

# Enable logging
logger:
  logs:
    duty_cycle: ERROR
    sensor: ERROR

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
  
status_led:
  pin:
    number: GPIO2
    inverted: true
      
fan:
  - platform: rowenta_fan
    name: $upper_hostname