substitutions:
  hostname: rowenta_fan
  upper_hostname: "Ventilador Pié"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp12e

<<: !include .common.wifi.yaml

# Enable logging
logger:
  logs:
    duty_cycle: ERROR
    sensor: ERROR

web_server:
  port: 80
  
status_led:
  pin:
    number: GPIO2
    inverted: true
      
fan:
  - platform: rowenta_fan
    name: $upper_hostname