esphome:
  name: rs485-test

esp8266:
  board: nodemcuv2
  
external_components:
  - source: overriden_components
    components: [ uart ]

<<: !include .common.wifi.yaml

# Enable logging
logger:
  #level: VERBOSE
  baud_rate: 0

uart:
  - id: rs485_uart
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600
  - id: v9261f_uart
    rx_pin: GPIO4
    tx_pin: GPIO5
    baud_rate: 4800
    parity: ODD
    stop_bits: 1
    debug:

# Register the Tuya MCU connection
#tuya:

sensor:
  - platform: v9261f
    uart_id: v9261f_uart
    voltage:
      name: 'V9261F Voltage'
    current:
      name: 'V9261F Current'
    power:
      name: 'V9261F Power'
    energy:
      name: 'V9261F Energy'
    update_interval: 3s