substitutions:
  hostname: test_multiwattmeter
  upper_hostname: "Multi Wattmeter"
  meter1_name: Meter1
  meter2_name: Meter2
  meter3_name: Meter3
  sensor_interval: 3s

esphome:
  name: $hostname
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $hostname
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

status_led:
  pin:
    number: GPIO2
    inverted: true
    
# Enable time component to reset energy at midnight
time:
  - platform: homeassistant

uart:
  - tx_pin: TX
    rx_pin: RX
    baud_rate: 9600
    stop_bits: 1

sensor:
  - platform: uptime
    name: "$upper_hostname Uptime"
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s
  - platform: pzemac
    update_interval: $sensor_interval
    address: 1
    current:
      name: "$meter1_name Current"
    voltage:
      name: "$meter1_name Voltage"
    power:
      name: "$meter1_name Power"
      id: meter1_power
    frequency:
      name: "$meter1_name Frequency"
    power_factor:
      name: "$meter1_name Power Factor"
    #energy:
    #  name: "$meter1_name Total Energy"
    #  filters:
    #    - multiply: 0.001   # convert Wh to kWh
    #  accuracy_decimals: 3
    #  unit_of_measurement: kWh
  - platform: total_daily_energy
    name: "$meter1_name Total Energy Today"
    power_id: meter1_power
    filters:
      - multiply: 0.001   # convert Wh to kWh
    accuracy_decimals: 3
    unit_of_measurement: kWh
  - platform: pzemac
    update_interval: $sensor_interval
    address: 2
    current:
      name: "$meter2_name Current"
    voltage:
      name: "$meter2_name Voltage"
    power:
      name: "$meter2_name Power"
      id: meter2_power
    frequency:
      name: "$meter2_name Frequency"
    power_factor:
      name: "$meter2_name Power Factor"
    #energy:
    #  name: "$meter2_name Total Energy"
    #  filters:
    #    - multiply: 0.001   # convert Wh to kWh
    #  accuracy_decimals: 3
    #  unit_of_measurement: kWh
  - platform: total_daily_energy
    name: "$meter2_name Total Energy Today"
    power_id: meter2_power
    filters:
      - multiply: 0.001   # convert Wh to kWh
    accuracy_decimals: 3
    unit_of_measurement: kWh
  - platform: pzemac
    update_interval: $sensor_interval
    address: 3
    current:
      name: "$meter3_name Current"
    voltage:
      name: "$meter3_name Voltage"
    power:
      name: "$meter3_name Power"
      id: meter3_power
    frequency:
      name: "$meter3_name Frequency"
    power_factor:
      name: "$meter3_name Power Factor"
    #energy:
    #  name: "$meter3_name Total Energy"
    #  filters:
    #    - multiply: 0.001   # convert Wh to kWh
    #  accuracy_decimals: 3
    #  unit_of_measurement: kWh
  - platform: total_daily_energy
    name: "$meter3_name Total Energy Today"
    power_id: meter3_power
    filters:
      - multiply: 0.001   # convert Wh to kWh
    accuracy_decimals: 3
    unit_of_measurement: kWh
