substitutions:
  hostname: towel_warmer
  upper_hostname: "Toallero"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

<<: !include .common.wifi.yaml

# Enable logging
logger:
#  baud_rate: 0

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s
  - platform: dht
    pin: GPIO14
    model: DHT11
    temperature:
      name: "Bathroom Temperature"
    humidity:
      name: "Bathroom Humidity"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

script:
  - id: timer_off
    then:
    - delay: 60min
    - switch.turn_off: relay

switch:
  - platform: gpio
    name: $upper_hostname
    id: relay
    icon: mdi:radiator
    pin: GPIO12
    on_turn_on:
      - script.execute: timer_off
    on_turn_off:
      - script.stop: timer_off