substitutions:
  hostname: victor-s20-2
  upper_hostname: "Árbol Navidad"
  hass_icon: mdi:pine-tree
  time_off: 4h
  #upper_hostname: "Riego"
  #hass_icon: mdi:watering-can
  #time_off: 2min

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $hostname
    password: !secret wifi_ap_password
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
time:
  - platform: homeassistant
    id: hass_time
#    on_time:
#      # Every day at 00:00:00
#      - seconds: 0
#        minutes: 0
#        hours: 0
#        then:
#          - switch.turn_on: relay
#      # Every day at 00:09:00
#      - seconds: 0
#        minutes: 0
#        hours: 9
#        then:
#          - switch.turn_on: relay
#      # Every day at 00:17:00
#      - seconds: 0
#        minutes: 0
#        hours: 17
#        then:
#          - switch.turn_on: relay
    
sensor:
  - platform: wifi_signal
    name: "$upper_hostname WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

script:
  - id: timer_off
    then:
    - delay: $time_off
    - switch.turn_off: relay

switch:
  - platform: gpio
    name: $upper_hostname
    icon: $hass_icon
    pin: GPIO12
    id: relay
    on_turn_on:
      - script.execute: timer_off
    on_turn_off:
      - script.stop: timer_off