esphome:
  name: victor_cover
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: true
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
    
status_led:
  pin:
    number: GPIO2
    inverted: yes

binary_sensor:
- platform: gpio
  pin:
    number: GPIO14
    inverted: true
  id: switch_close
  on_press:
    then:
      - cover.stop: my_cover
      - cover.close: my_cover
  on_release:
    then:
      - cover.stop: my_cover
- platform: gpio
  pin:
    number: GPIO4
    inverted: true
  id: switch_open
  on_press:
    then:
      - cover.stop: my_cover
      - cover.open: my_cover
  on_release:
    then:
      - cover.stop: my_cover

output:
- platform: gpio
  pin: GPIO13
  id: cover_up
- platform: gpio
  pin: GPIO5
  id: cover_down

cover:
- platform: time_based
  name: "victor_cover"
  id: my_cover
  open_action:
    - output.turn_on: cover_up
    - output.turn_off: cover_down
  open_duration: 17s
  close_action:
    - output.turn_off: cover_up
    - output.turn_on: cover_down
  close_duration: 16s
  stop_action:
    - output.turn_off: cover_up
    - output.turn_off: cover_down