substitutions:
  hostname: y_039s
  upper_hostname: "Y-039S"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

<<: !include .common.wifi.yaml

# Enable logging
logger:
  baud_rate: 0

# Enable Web server
web_server:
  port: 80

uart:
  rx_pin: RX
  baud_rate: 4800

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
    
status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  # Uptime sensor
  - platform: uptime
    name: "$upper_hostname Uptime"
  # WiFi Signal sensor
  - platform: wifi_signal
    name: "$upper_hostname Wifi Signal"
    update_interval: 10s
  # Power sensor
  - platform: cse7766
    # Current sensor
    current:
      name: "$upper_hostname Current"
      unit_of_measurement: A
      accuracy_decimals: 3
    # Voltage sensor
    voltage:
      name: "$upper_hostname Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
    # Power sensor
    power:
      id: power
      name: "$upper_hostname Power"
      unit_of_measurement: W
      accuracy_decimals: 0
  # Total daily energy sensor
  - platform: total_daily_energy
    name: "$upper_hostname Energy Today"
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    id: button
    pin:
      number: GPIO12
    on_press:
      - switch.toggle: relay
  
  # Connected device is power on
  - platform: template
    name: "$upper_hostname On"
    lambda: |-
        return id(power).state > 1;
    
script:
  - id: timer_off
    then:
    - delay: 120min
    - switch.turn_off: relay

switch:
  # Switch to toggle the relay
  - platform: gpio
    id: relay
    name: $upper_hostname
    pin: GPIO14
    on_turn_on:
      - light.turn_on: led
      #- script.execute: timer_off
    on_turn_off:
      - light.turn_off: led
      #- script.stop: timer_off

output:
  # Relay state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO13
      inverted: true

light:
  # Relay state light
  - platform: monochromatic
    output: state_led
    id: led